
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]

modId="realistic_metals"

version="1.1.9"

displayName="Realistic Metals"

authors="IndEvo Studio"


description='''Real ores and gems, tools and armor.'''

[[dependencies.realistic_metals]]

modId="forge"

mandatory=true

versionRange="${forge_version_range}"

ordering="NONE"

side="BOTH"

[[dependencies.realistic_metals]]
modId="minecraft"
mandatory=true

versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

